services:
  quiz_manager_app:
    container_name: quiz_manager_app
    build:
      context: .
      dockerfile: ./infra/php/Dockerfile
    volumes:
      - ./backend:/var/www/html
      - ./infra/php/php.ini:/usr/local/etc/php/php.ini

  quiz_manager_web:
    container_name: quiz_manager_web
    build:
      context: .
      dockerfile: ./infra/nginx/Dockerfile
    ports:
      - "8000:80"
      - "3000:3000"
    depends_on:
      - quiz_manager_app
    volumes:
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/var/www/html

  quiz_manager_db:
    container_name: quiz_manager_db
    build:
      context: .
      dockerfile: ./infra/mysql/Dockerfile
    platform: linux/x86_64
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: quiz-manager
      MYSQL_USER: quiz-manager
      MYSQL_PASSWORD: secretapp
      MYSQL_ROOT_PASSWORD: secretapp
      TZ: "Asia/Tokyo"
    volumes:
      - quiz-mysql-volume:/var/lib/mysql

  quiz_manager_db_test:
    container_name: quiz_manager_db_test
    build:
      context: .
      dockerfile: ./infra/mysql/Dockerfile
    platform: linux/x86_64
    environment:
      MYSQL_DATABASE: test_quiz-manager
      MYSQL_USER: test_quiz-manager
      MYSQL_PASSWORD: secretapp
      MYSQL_ROOT_PASSWORD: secretapp
      TZ: "Asia/Tokyo"
    depends_on:
      - quiz_manager_db

  phpmyadmin_quiz:
    image: phpmyadmin/phpmyadmin
    platform: linux/x86_64
    environment:
      PMA_HOST: quiz_manager_db
      PMA_USER: root
      PMA_PASSWORD: secretapp
    ports:
      - "8080:80"
    depends_on:
      - quiz_manager_db

volumes:
  quiz-mysql-volume: